In [1]:
import sympy as sp
import numpy as np
from constants import *


In [3]:
exp = sp.simplify("x*T**2*100 - 101")
exp

100*T**2*x - 101

In [4]:
T = sp.symbols("T")
x = sp.symbols("x")
exp.subs([(x, 2), (T, 3)])
# type(T)

1699

In [5]:
(1 - x) * 1000

10.0*x

In [18]:
f = sp.lambdify((x, T), exp, "numpy")
f
f(np.arange(10), np.arange(1,11))

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [19]:
f = (1 - T)**3
f.subs(T, 3)
sp.expand(f)

-T**3 + 3*T**2 - 3*T + 1

In [7]:
def hillert_jarl_func(tau, phase="fcc"):
    phase = phase.lower()
    result = [key for key in P_VALUES.keys() if key in phase]
    if not result:
        return 0
    phase = result[0]
    p = P_VALUES[phase]
    denominator = 518 / 1125 + (11692 / 15975) * (1 / p - 1)
    return \
        sp.Piecewise(
            (1 - ((79 / tau / 140 * p) + 474 / 497 * (1 / p - 1) * (tau ** 3 / 6 + tau ** 9 / 135 + tau ** 15 / 600)) \
            / denominator, tau < 1),
            (- (tau ** (-5) / 10 + tau ** (-15) / 315 + tau ** (-25) / 1500) / denominator, True))


In [8]:
hillert_jarl_func(T)

Piecewise((-0.00174491240370669*T**15 - 0.00775516623869638*T**9 - 0.174491240370669*T**3 + 1 - 0.0674505583610618/T, T < 1), (-0.0426902268107986/T**5 - 0.00135524529558091/T**15 - 0.000284601512071991/T**25, True))

In [10]:
cond_expr = sp.Piecewise((x**3, x>0), (1/x**3, True))
cond_expr_f = sp.lambdify(x, cond_expr, "numpy")
cond_expr_f(np.array([3, 1, -2, 5, -4, 0, 1, -1, -10]))
# cond_expr(x/10)

<string>:2: RuntimeWarning: divide by zero encountered in power


array([ 2.7000e+01,  1.0000e+00, -1.2500e-01,  1.2500e+02, -1.5625e-02,
               inf,  1.0000e+00, -1.0000e+00, -1.0000e-03])

# abnormal case

In [70]:
def hillert_jarl_func(tau, phase="fcc"):
    phase = phase.lower()
    result = [key for key in P_VALUES.keys() if key in phase]
    if not result:
        return 0
    phase = result[0]
    p = P_VALUES[phase]
    denominator = 518 / 1125 + (11692 / 15975) * (1 / p - 1)
    return  - (tau ** (-5) / 10 + tau ** (-15) / 315 + tau ** (-25) / 1500) / denominator
    # return \
    #     sp.Piecewise(
    #         (1 - ((79 / tau / 140 / p) + 474 / 497 * (1 / p - 1) * (tau ** 3 / 6 + tau ** 9 / 135 + tau ** 15 / 600)) \
    #         / denominator, tau < 1),
    #         (- (tau ** (-5) / 10 + tau ** (-15) / 315 + tau ** (-25) / 1500) / denominator, True))

In [71]:
T = sp.symbols("T")
x = sp.symbols("x")
gibbs_energy_expr = sp.simplify(hillert_jarl_func(T/800))

# psi symbol corresponds to the thermodynamic factor.
# psi_expr = (1 - x) * x / GAS_CONSTANT / T * sp.diff(gibbs_energy_expr, (x, 2))
psi_expr = gibbs_energy_expr

psi_func= sp.lambdify(T, psi_expr, "numpy")
# print(func_str.split(":")[-1].split("return")[-1].strip())
psi_func(diffusion_data.data["temp_kelvin"])

18     1.608722e+50
19     1.608722e+50
20     1.608722e+50
21     1.608722e+50
22     1.608722e+50
           ...     
440   -1.414270e+50
441   -1.414270e+50
442   -1.414270e+50
443   -1.414270e+50
444   -1.414270e+50
Name: temp_kelvin, Length: 262, dtype: float64

In [74]:
psi_expr

-(13988733521362.5*T**20 + 4.76834547513578e+40*T**10 + 1.07519411326623e+69)/T**25

In [73]:
psi_expr.subs(T, 1383), psi_func(np.array([1383])), psi_func

(-0.00276519252053948,
 array([-4.95506936e+60]),
 <function _lambdifygenerated(T)>)

In [9]:
T = sp.symbols("T")
x = sp.symbols("x")
gibbs_energy_expr = sp.Piecewise((-0.00174491240370669*T**15/(x*(1 - x)*(1400*x - 800*(1 - 2*x)**2 + 1500) - 416*x + 1043)**15 - 0.00775516623869638*T**9/(x*(1 - x)*(1400*x - 800*(1 - 2*x)**2 + 1500) - 416*x + 1043)**9 - 0.174491240370669*T**3/(x*(1 - x)*(1400*x - 800*(1 - 2*x)**2 + 1500) - 416*x + 1043)**3 + 1 - 0.86033875460538*(x*(1 - x)*(1400*x - 800*(1 - 2*x)**2 + 1500) - 416*x + 1043)/T, T/(x*(1 - x)*(1400*x - 800*(1 - 2*x)**2 + 1500) - 416*x + 1043) < 1), (-0.0426902268107986*(x*(1 - x)*(1400*x - 800*(1 - 2*x)**2 + 1500) - 416*x + 1043)**5/T**5 - 0.00135524529558091*(x*(1 - x)*(1400*x - 800*(1 - 2*x)**2 + 1500) - 416*x + 1043)**15/T**15 - 0.000284601512071991*(x*(1 - x)*(1400*x - 800*(1 - 2*x)**2 + 1500) - 416*x + 1043)**25/T**25, True))

# psi symbol corresponds to the thermodynamic factor.
# psi_expr = (1 - x) * x / GAS_CONSTANT / T * sp.diff(gibbs_energy_expr, (x, 2))
psi_expr = gibbs_energy_expr

psi_func = sp.lambdify((x, T), psi_expr, "numpy")
psi_func(diffusion_data.data["comp_A_mf"], diffusion_data.data["temp_kelvin"])


array([ 1.34489378e+51,  3.14883869e+53,  1.03452815e+55,  7.34514379e+55,
       -3.53193304e-02,  9.86680474e+55,  2.70365019e+55,  3.93879635e+54,
        4.92982713e+53,  5.59836821e+51,  1.31076214e+54,  4.30641410e+55,
        3.05755147e+56,  6.09325280e+56,  4.10723932e+56,  1.12544422e+56,
        1.63959657e+55,  2.05213140e+54, -6.65003040e+51, -1.55699085e+54,
       -5.11538069e+55, -3.63191728e+56, -7.23787982e+56, -4.87879062e+56,
       -1.33686067e+56, -1.94759734e+55, -2.43762748e+54,  5.02164845e+51,
        1.17573307e+54,  3.86278588e+55,  2.74257570e+56,  5.46555216e+56,
        3.68412923e+56,  1.00950581e+56,  1.47069240e+55,  1.84072967e+54,
       -1.83611086e+51, -4.29893946e+53, -1.41238543e+55, -1.00279283e+56,
       -1.99841940e+56, -1.34706158e+56, -3.69114764e+55, -5.37742600e+54,
       -6.73042682e+53, -5.37852658e+55, -9.53338027e+55, -3.75772221e-02,
       -3.74053327e-02, -1.01482955e+56, -6.82688005e+55, -3.38355743e+55,
       -1.23862190e+55, -